version: '3'
services:

  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      
  product-service:
    build: ./product-service
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      
  order-service:
    build: ./order-service
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
